### ISSUE TITLE
Port to Blue Pill stm32

### ISSUE THREAD

**Issue by thomasbra1** [liuyuf78fk/sega-saturn-to-USB_Game-controller-V2.0#1]
Could this be ported to the Blue Pill easily?  The dev boards are cheap and abundant.  Thanks.

**Comment by liuyuf78fk** [comment]
Yes. You only need to solder 10 wires without changing the program.

发自我的 iPhone

> 在 2019年12月21日，上午7:23，thomasbra1 <notifications@github.com> 写道：
> 
> Blue Pill

**Comment by liuyuf78fk** [comment]
This code is suitable for Blue Pill ，Just solder the corresponding leads according to the circuit schematic diagram of  in the compression package.

**Comment by thomasbra1** [comment]
Thanks for the information.  This looks like a good base to add other classic controllers.
